[package]
name = "tpt-opt-systems"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["optimization", "solver", "umbrella", "milp", "multi-objective"]
categories = ["science::math", "algorithms"]
documentation = "https://docs.rs/tpt-opt-systems"

[dependencies]

[features]
default = ["std"]
std = []
